# Dockerfile for Frontend Build
FROM node:16.13-alpine3.15 AS build

WORKDIR /app

COPY frontend/package.json  frontend/yarn.lock /app/

RUN npm install

COPY frontend /app
RUN npm run build

FROM nginx:1.22-alpine

COPY --from=build /app/build /usr/share/nginx/html

