export const DETAILED_ALERT = 'DETAILED_ALERT'
export const SET_ALERTS_NUMBER = 'SET_ALERTS_NUMBER'
export const SET_FOUND_ALERTS = 'SET_ALERTS_TO_DISPLAY'
export const RECHECK_ALL_ALERTS = 'RECHECK_ALL_ALERTS'