---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
    spec:
      imagePullSecrets:
      - name: registry-secret
      initContainers:
      - name: check-mongodb
        image: busybox:1.31
        command:
        - ash
        - "-c"
        - |
          until nc -z tenis-mongodb 27017
          do
              echo "MongoDB is not ready"
              sleep 1
          done
      containers:
      - name: {{ .Chart.Name }}-backend
        image: {{ $.Values.werf.image.backend }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        env:
        - name: MONGO_HOST
          value: {{ .Chart.Name }}-mongodb
        - name: MONGO_DATABASE
          value: {{ pluck .Values.werf.env .Values.mongodb.env.INIT_DB | first | default .Values.mongodb.env.INIT_DB._default }}
        - name: API_TOKEN
          value: {{ pluck .Values.werf.env .Values.mongodb.env.API_TOKEN | first | default .Values.mongodb.env.API_TOKEN._default }}
        livenessProbe:
          httpGet:
            path: /healz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        startupProbe:
          httpGet:
            path: /healz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerance }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-backend
