apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-env-config
  labels:
    app: {{ .Chart.Name }}-frontend
data:
  env-config.js: |-
    window._env_ = {
      API_SERVER: "api.{{ .Values.env_url }}",
      PORT: "443"
    };
