apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{ .Chart.Name }}-ingress
  labels:
    component: frontend
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.env_url }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-frontend
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.env_url }}
    secretName: {{ .Chart.Name }}-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-certificate
spec:
  dnsNames:
  - {{ .Values.env_url }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ .Chart.Name }}-secret
  usages:
  - digital signature
  - key encipherment
