apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.ivinco.com"
  name: {{ .Chart.Name }}-frontend-ingress
  labels:
    component: frontend
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.env_url }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.env_url }}
      secretName: {{ .Chart.Name }}-secret


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.ivinco.com"
  name: {{ .Chart.Name }}-api-ingress
  labels:
    component: frontend
spec:
  ingressClassName: nginx
  rules:
    - host: api.{{ .Values.env_url }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Chart.Name }}-backend
                port:
                  number: 8000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api.{{ .Values.env_url }}
      secretName: {{ .Chart.Name }}-api-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-certificate
spec:
  dnsNames:
    - {{ .Values.env_url }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ .Chart.Name }}-secret
  usages:
    - digital signature
    - key encipherment

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-api-certificate
spec:
  dnsNames:
    - api.{{ .Values.env_url }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ .Chart.Name }}-api-secret
  usages:
    - digital signature
    - key encipherment
