apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mongodb-init
  labels:
    app: {{ .Chart.Name }}-mongodb
data:
  init-script.sh: |-
    mongod --fork --logpath /var/log/mongod.log --bind_ip_all
    set -e
    until mongosh --eval "print(\"Connection established, mongodb should be up\")"; do
      echo waiting for mongo
      sleep 2
    done

    mongosh {{ pluck .Values.werf.env .Values.mongodb.env.INIT_DB | first | default .Values.mongodb.env.INIT_DB._default }} --eval 'if (db.getCollectionNames().includes("users") === false) {
      db.createCollection("users", { capped: true, size: 5242880, max: 5000 });
    }'

    mongosh {{ pluck .Values.werf.env .Values.mongodb.env.INIT_DB | first | default .Values.mongodb.env.INIT_DB._default }} --eval 'if (db.users.findOne({ name: "{{ pluck .Values.werf.env .Values.mongodb.env.INIT_USER_NAME | first | default .Values.mongodb.env.INIT_USER_NAME._default }}" }) === null) {
      db.users.insertOne({
        name: "{{ pluck .Values.werf.env .Values.mongodb.env.INIT_USER_NAME | first | default .Values.mongodb.env.INIT_USER_NAME._default }}",
        email: "{{ pluck .Values.werf.env .Values.mongodb.env.INIT_USER_EMAIL | first | default .Values.mongodb.env.INIT_USER_EMAIL._default }}",
        password: "{{ pluck .Values.werf.env .Values.mongodb.env.INIT_PASSWORD | first | default .Values.mongodb.env.INIT_PASSWORD._default }}",
        active: true,
        commentReplaceRules: {
        {{- $length := len .Values.usersCommentReplaceRules -}}
        {{- range $index, $element := .Values.usersCommentReplaceRules }}
          {{ $element.prefix | quote }}: {{ printf "%s$1" $element.site | quote }}{{ if ne (add1 $index) $length }},{{ end }}
        {{- end }}
        }
      });
    }'

    mongosh $INIT_DB --eval 'db.current.createIndex({ project: 1, host: 1, alertName: 1 }, { unique: true })'
    mongod --shutdown
