backend:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

frontend:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

monbodb:
  env:
    INIT_DB:
      _default: "tenis"
    INIT_USER_NAME:
      _default: "Admin"
    INIT_USER_EMAIL:
      _default: "sys@ivinco.com"
