backend:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"



  nodeSelector: {}

  tolerations: []

  affinity: {}

frontend:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"


  nodeSelector: {}

  tolerations: []

  affinity: {}

mongodb:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"


  env:
    INIT_DB:
      _default: "tenis"
    INIT_USER_NAME:
      _default: "Admin"
    INIT_USER_EMAIL:
      _default: "sys@ivinco.com"
