backend:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"



  nodeSelector: {}

  tolerations: []

  affinity: {}

frontend:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"


  nodeSelector: {}

  tolerations: []

  affinity: {}

mongodb:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"


  env:
    INIT_DB:
      _default: "tenis"
    INIT_USER_NAME:
      _default: "Admin"
    INIT_USER_EMAIL:
      _default: "sys@ivinco.com"

usersCommentReplaceRules:
- prefix: 'TT\\d+'
  site: "https://ivinco.atlasian.net/browse/"
- prefix: 'BR\\d+'
  site: "https://ivinco.atlasian.net/browse/"
- prefix: 'SG\\d+'
  site: "https://socialgist.atlasian.net/browse/"
