apiVersion: v1
kind: ConfigMap
metadata:
  name: tenis-nginx-config
  labels:
    component: frontend
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /dev/stderr;
    pid /run/nginx.pid;
    daemon off;
    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;
    events {
        worker_connections 1024;
    }
    http {
        log_format json_combined escape=json '{'
          '"time_local":"$time_local",'
          '"remote_addr":"$remote_addr",'
          '"remote_user":"$remote_user",'
          '"request":"$request",'
          '"status": "$status",'
          '"body_bytes_sent":"$body_bytes_sent",'
          '"request_time":"$request_time",'
          '"http_referrer":"$http_referer",'
          '"http_user_agent":"$http_user_agent",'
          '"http_x_forwarded_for":"$http_x_forwarded_for"'
        '}';

        access_log  /dev/stdout  json_combined;
        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;
        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;
        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        include /etc/nginx/conf.d/*.conf;
        server {
            listen       3000 default_server;
            listen       [::]:3000 default_server;
            server_name  _;
            root         /usr/share/nginx/html;
            # Load configuration files for the default server block.
            include /etc/nginx/default.d/*.conf;
            location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                try_files $uri /index.html;
            }
            error_page 404 /404.html;
            location = /404.html {
            }
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
            }
        }
    }
---
# Source: tenis/templates/frontend-nginx-env-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenis-nginx-env-config
  labels:
    app: tenis-frontend
data:
  env-config.js: |-
    window._env_ = {
      API_SERVER: "https://api.tenis.k8s-test.***.com", # TODO paste from variable $API_SERVER (?)
      BACKEND_PORT: "443" # TODO decide if needs to be variable as wekk
    };
---
# Source: tenis/templates/mongodb-init-script-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenis-mongodb-init
  labels:
    app: tenis-mongodb
data:
  init-script.sh: |-
    mongod --fork --logpath /var/log/mongod.log --bind_ip_all
    set -e
    until mongosh --eval "print(\"Connection established, mongodb should be up\")"; do
      echo waiting for mongo
      sleep 2
    done

    mongosh tenis --eval 'if (db.getCollectionNames().includes("users") === false) {
      db.createCollection("users", { capped: true, size: 5242880, max: 5000 });
    }'

    mongosh tenis --eval 'if (db.users.findOne({ name: "Admin" }) === null) {
      db.users.insertOne({
        name: "Admin",
        email: "sys@example.com",
        password: "#TODO password, mb from var",
        active: true,
        commentReplaceRules: {},
        userProjects: ["Test"]
      });
    }'

    mongosh tenis --eval 'db.current.createIndex({ project: 1, host: 1, alertName: 1 }, { unique: true })'
    mongod --shutdown
---
# Source: tenis/templates/backend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: tenis-backend
  labels:
    app: tenis-backend
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: tenis-backend
---
# Source: tenis/templates/frontend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: tenis-frontend
  labels:
    app: tenis-frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: tenis-frontend
---
# Source: tenis/templates/mongodb-statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: tenis-mongodb
  labels:
    app: tenis-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: tenis-mongodb
---
# Source: tenis/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenis-backend
  labels:
    app: tenis-backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenis-backend
  template:
    metadata:
      labels:
        app: tenis-backend
    spec:
      initContainers:
        - name: check-mongodb
          image: busybox:1.31
          command:
            - ash
            - "-c"
            - |
              until nc -z $MONGO_HOST 27017 #TODO тут tenis-mongodb был указан прямо так, надо убедиться что работает и тоже донести в остальной чарт
              do
                  echo "MongoDB is not ready"
                  sleep 1
              done
      containers:
        - name: tenis-backend
          image: docker-registry.***.com/tenis:88c2e8d5cf003c74969404aea44bd170aa2a176ea3502bccd86b2060-1722439006797 #TODO-image
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: MONGO_HOST
              value: tenis-mongodb
            - name: MONGO_DATABASE
              value: tenis
            - name: API_TOKEN
              value: some-token (?) #TODO найти как генерится этот токен
          livenessProbe:
            httpGet:
              path: /healz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /healz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
---
# Source: tenis/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenis-frontend
  labels:
    app: tenis-frontend
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenis-frontend
  template:
    metadata:
      labels:
        app: tenis-frontend
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: tenis-frontend
          image: docker-registry.***.com/tenis:b566e3d2647ad91eb842ab929e5474de48aed269a5e94264dceb9139-1722439056167 #TODO-image
          imagePullPolicy: IfNotPresent
          command:
            - nginx
            - -e
            - /dev/stderr
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-env-config
              mountPath: /usr/share/nginx/html/env-config.js
              subPath: env-config.js
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: nginx-config-volume
          configMap:
            name: tenis-nginx-config
        - name: nginx-env-config
          configMap:
            name: tenis-nginx-env-config
---
# Source: tenis/templates/mongodb-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tenis-mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: tenis-mongodb
  template:
    metadata:
      labels:
        app: tenis-mongodb
    spec:
      imagePullSecrets:
        - name: registry-secret
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: mongo-init
          image: docker-registry.***.com/tenis:7f561e733e69c677b2b5331abbd1131ddfa7b66bd3e5076e1d18ec52-1700750629409 #TODO-image
          command: ["/bin/sh", "/tmp/init-script.sh"]
          volumeMounts:
            - name: tenis-mongodb-init
              mountPath: /tmp/init-script.sh
              subPath: init-script.sh
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: INIT_DB
              value: tenis
            - name: INIT_USER_NAME
              value: Admin
            - name: INIT_USER_EMAIL
              value: sys@***.com
            - name: INIT_PASSWORD
              value: # TODO password
      containers:
        - name: mongo
          image: docker-registry.***.com/tenis:7f561e733e69c677b2b5331abbd1131ddfa7b66bd3e5076e1d18ec52-1700750629409 #TODO-image
          command:
            - mongod
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: tenis-mongodb-init
          configMap:
            name: tenis-mongodb-init
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 10Gi
---
# Source: tenis/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.***.com" #TODO cors
  name: tenis-frontend-ingress
  labels:
    component: frontend
spec:
  ingressClassName: nginx
  rules:
    - host: tenis.k8s-test.***.com
      http:
        paths:
          - backend:
              service:
                name: tenis-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - tenis.k8s-test.***.com
      secretName: tenis-secret
---
# Source: tenis/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.***.com"  #TODO cors
  name: tenis-api-ingress
  labels:
    component: frontend
spec:
  ingressClassName: nginx  #TODO ingress class
  rules:
    - host: api.tenis.k8s-test.***.com
      http:
        paths:
          - backend:
              service:
                name: tenis-backend
                port:
                  number: 8000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api.tenis.k8s-test.***.com
      secretName: tenis-api-secret

