name: Deploy to prod

env:
  WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
  WERF_REPO: registry.ivinco.com/tenis

on:
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.ivinco.com
          username: ${{ secrets.REGISTRY_SECRET_USER }}
          password: ${{ secrets.REGISTRY_SECRET_PASSWORD }}

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Build and Publish
        run: |
          . $(werf ci-env github --as-file)
          werf build


  render-and-lint:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.ivinco.com
          username: ${{ secrets.REGISTRY_SECRET_USER }}
          password: ${{ secrets.REGISTRY_SECRET_PASSWORD }}

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Render chart
        run: werf render --env prod --ignore-secret-key
        env:
          WERF_SET_ENV_URL: "env_url=tenis.k8s-test.ivinco.com"

      - name: Lint chart
        run: werf helm lint .helm


  converge:
    if: github.event.pull_request.merged == true
    needs: render-and-lint
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.ivinco.com
          username: ${{ secrets.REGISTRY_SECRET_USER }}
          password: ${{ secrets.REGISTRY_SECRET_PASSWORD }}

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
          env: prod
        env:
          WERF_SET_ENV_URL: "env_url=tenis.k8s-test.ivinco.com"
          WERF_NAMESPACE: tenis-prod
          WERF_RELEASE: tenis-prod
